command: ["npx", "n8n"]
volumes:
  - from: "/Volumes/main/n8n_app/n8n_data"
    to: "/home/n8n/.n8n"
environment:
  - name: N8N_HOST
    value: "0.0.0.0"
  - name: N8N_PORT
    value: "5678"
  - name: N8N_USER_FOLDER
    value: "/home/n8n/.n8n"
  - name: GENERIC_TIMEZONE
    value: "Europe/Rome"
  - name: DB_TYPE
    value: "sqlite"
  - name: DB_SQLITE_POOL_SIZE
    value: "5"
  - name: N8N_RUNNERS_ENABLED
    value: "true"
  - name: N8N_BLOCK_ENV_ACCESS_IN_NODE
    value: "false"
  - name: N8N_GIT_NODE_DISABLE_BARE_REPOS
    value: "false"